[build]
  publish = "site"
  command = "pip3 install -r requirements.txt && python3 build.py"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/forge"
  to = "https://forgeprole.netlify.app"
  status = 301
  force = true

[[redirects]]
  from = "/forge/*"
  to = "https://forgeprole.netlify.app/:splat"
  status = 301
  force = true
