const {test}=require("node:test");const assert=require("node:assert/strict");const vm=require("node:vm"),fs=require("node:fs"),sandbox={module:{exports:{}}};vm.runInNewContext(fs.readFileSync(require("node:path").join(__dirname,"../assets/reference-engine.js"),"utf8"),sandbox);const E=sandbox.module.exports;
const near=(a,b,epsilon=1e-7)=>assert.ok(Math.abs(a-b)<epsilon, a+" != "+b);
const base={frequencyMHz:2400,distanceKm:1,txDbm:20,txGainDbi:0,rxGainDbi:0,lossDb:0,sensitivityDbm:-100};
test("RF example checked against wavelength/spreading expression",()=>{const r=E.rf(base);const exact=20*Math.log10(4*Math.PI*1000/(299792458/2400e6));assert.ok(Math.abs(r.fsplDb-exact)<.05);near(r.fsplDb,100.00422483423211);near(r.receivedDbm,20-r.fsplDb);near(E.rf({...base,distanceKm:2}).fsplDb-r.fsplDb,6.020599913279624);near(E.rf({...base,lossDb:8}).marginDb,r.marginDb-8);});
test("invalid/nonfinite values cannot yield plausible output",()=>{for(const v of ["",null,0,-1,NaN,Infinity,"abc"])assert.throws(()=>E.rf({...base,frequencyMHz:v}));assert.throws(()=>E.rf({...base,lossDb:-1}));assert.throws(()=>E.rf({...base,distanceKm:1e-12}));assert.throws(()=>E.battery({voltageV:10,capacityMah:5000,averageW:0,usablePercent:80,reservePercent:20}));assert.throws(()=>E.power({railV:5,loadA:2,limitA:3,efficiencyPercent:101}));});
test("energy/runtime and load overload have independent expected values",()=>{const b=E.battery({voltageV:10,capacityMah:5000,averageW:100,usablePercent:80,reservePercent:25});near(b.nominalWh,50);near(b.availableWh,30);near(b.minutes,18);near(E.battery({voltageV:10,capacityMah:5000,averageW:100,usablePercent:80,reservePercent:100}).minutes,0);const p=E.power({railV:5,loadA:4,limitA:3,efficiencyPercent:80});near(p.outputW,20);near(p.inputW,25);near(p.headroomA,-1);});
test("wavelength is a dimensional reference and interfaces are declarations",()=>{near(E.antenna({frequencyMHz:100}).wavelengthM,2.99792458);assert.match(E.interfacePlan({requiredProtocol:"UART",providedProtocol:"uart",requiredV:3.3,providedV:5}).candidate,/conflict/);assert.match(E.interfacePlan({requiredProtocol:"UART",providedProtocol:"uart",requiredV:3.3,providedV:3.3}).candidate,/testing still required/);});
test("query does not turn unknown values into zero, substring values preserve units",()=>{const rows=[{id:"1",kind:"component",group:"power",title:"Rail 5 V",status:"unreviewed",fields:{Voltage:"5 V"}},{id:"2",kind:"component",group:"power",title:"Unknown rail",fields:{}}];assert.equal(E.query(rows,{text:"rail",field:"voltage",value:"5 v"}).length,1);assert.equal(E.query(rows,{text:"rail",field:"Voltage",value:"0"}).length,0);assert.equal(E.query(rows,{text:"rail unknown"})[0].id,"2");});
test("CSV quotes cells and neutralizes spreadsheet formula prefixes",()=>{const csv=E.csv([{id:"x",title:"=HYPERLINK()",statement:'a,"b"\\nc',status:"unreviewed",fields:{Voltage:"unknown"}}],"release");assert.ok(csv.includes('"\'=HYPERLINK()"'));assert.ok(csv.includes('a,""b""'));assert.ok(csv.startsWith('"release","id"'));});
