import {test} from "node:test";import assert from "node:assert/strict";import {DatabaseSync} from "node:sqlite";import {readFileSync,mkdtempSync,rmSync} from "node:fs";import {tmpdir} from "node:os";import {join} from "node:path";import {handle} from "../server/reports.mjs";
function setup(filename=":memory:"){const sql=new DatabaseSync(filename);for(const migration of ["0001_reports.sql","0002_attachments.sql","0003_autonomous_evidence.sql"])sql.exec(readFileSync(new URL("../migrations/"+migration,import.meta.url),"utf8"));return {sql,env:{REVIEW_TOKEN:"a-private-reviewer-secret",REPORTS:{prepare(query){let values={};return {bind(...args){values=Object.fromEntries(args.map((v,i)=>[i+1,v]));return this;},async first(){return sql.prepare(query).get(values)||null;},async all(){return {results:sql.prepare(query).all(values)};},async run(){return {meta:sql.prepare(query).run(values)};}};}}}};}
const payload=()=>({id:crypto.randomUUID(),receipt_token:"a".repeat(64),kind:"discrepancy",claim_id:"rf-fspl-2400-1",release:"test-release",commit:"a".repeat(40),source_path:"fundamentals/link-budgets.md",source_revision:"b".repeat(64),description:"Observed a mismatch in the cited value",consent:true});
const request=(path,method="GET",body,token,extra={})=>new Request("https://uas-handbook.com/api/"+path,{method,headers:{"content-type":"application/json",...(token?{authorization:"Bearer "+token}:{}),...extra},...(body===undefined?{}:{body:JSON.stringify(body)})});
test("durable receipt, exact retries, conflicts, no private data in status",async()=>{const {env,sql}=setup(),p=payload();assert.equal((await handle(request("reports","POST",p),env)).status,201);assert.equal((await handle(request("reports","POST",p),env)).status,200);assert.equal((await handle(request("reports","POST",{...p,description:"Changed"}),env)).status,409);const status=await handle(request("reports/"+p.id,"GET",undefined,p.receipt_token),env);assert.equal(status.status,200);assert.equal((await status.json()).description,undefined);assert.equal((await handle(request("reports/"+p.id,"GET",undefined,"wrong"),env)).status,404);assert.equal(sql.prepare("select count(*) n from reports").get().n,1);assert.notEqual(sql.prepare("select token_hash from reports").get().token_hash,p.receipt_token);sql.close();});
test("private reviewer auth and an evidence-to-publication history",async()=>{const {env,sql}=setup(),p=payload();await handle(request("reports","POST",p),env);assert.equal((await handle(request("review"),env)).status,401);let version=1;for(const state of ["triaged","accepted","correction-prepared"]){const r=await handle(request("review/"+p.id,"PATCH",{state,version,reason:"Evidence checked; software-only reproduction."},env.REVIEW_TOKEN),env);assert.equal(r.status,200,await r.text());version++;}
assert.equal((await handle(request("review/"+p.id,"PATCH",{state:"published",version,reason:"Published"},env.REVIEW_TOKEN),env)).status,400);
assert.equal((await handle(request("review/"+p.id,"PATCH",{state:"published",version,reason:"Approved exact release and verified custom domain",published_url:"https://uas-handbook.com/index.html#rf-fspl-2400-1",published_release:"release-123",publisher_approved:true,production_verified:true},env.REVIEW_TOKEN),env)).status,200);
const queue=await (await handle(request("review","GET",undefined,env.REVIEW_TOKEN),env)).json();assert.equal(queue.reports[0].data.commit,p.commit);assert.equal(queue.reports[0].data.source_revision,p.source_revision);assert.equal(queue.reports[0].history.length,4);assert.equal(queue.reports[0].state,"published");assert.equal(queue.reports[0].token_hash,undefined);sql.close();});
test("optimistic concurrency and duplicate target validation",async()=>{const {env,sql}=setup(),p=payload(),other=payload();await handle(request("reports","POST",p),env);await handle(request("reports","POST",other),env);const changed={state:"triaged",version:1,reason:"Triage"};const [a,b]=await Promise.all([handle(request("review/"+p.id,"PATCH",changed,env.REVIEW_TOKEN),env),handle(request("review/"+p.id,"PATCH",changed,env.REVIEW_TOKEN),env)]);assert.deepEqual([a.status,b.status].sort(),[200,409]);assert.equal((await handle(request("review/"+p.id,"PATCH",{state:"duplicate",version:2,reason:"Duplicate",duplicate_of:p.id},env.REVIEW_TOKEN),env)).status,400);assert.equal((await handle(request("review/"+p.id,"PATCH",{state:"duplicate",version:2,reason:"Same evidence",duplicate_of:other.id},env.REVIEW_TOKEN),env)).status,200);sql.close();});
test("validation, secrets, abuse control and unconfigured storage",async()=>{const {env,sql}=setup();for(const p of [{...payload(),consent:false},{...payload(),kind:"field-observation"},{...payload(),source_url:"javascript:alert(1)"},{...payload(),description:"-----BEGIN PRIVATE KEY-----"},{...payload(),description:"x".repeat(25000)}])assert.equal((await handle(request("reports","POST",p),env)).status,400);assert.equal((await handle(request("reports","POST",payload(),undefined,{origin:"https://evil.test"}),env)).status,403);for(let i=0;i<20;i++)assert.equal((await handle(request("reports","POST",payload()),env)).status,201);assert.equal((await handle(request("reports","POST",payload()),env)).status,429);assert.equal((await handle(request("reports","POST",payload()),{})).status,503);assert.equal((await (await handle(request("capabilities"),{})).json()).submission,false);sql.close();});
test("field observation is stored with exact declared conditions, not certified",async()=>{const {env,sql}=setup(),p={...payload(),kind:"field-observation",configuration:"Simulation provider v1, no hardware",observed_date:"2026-10-01",conditions:"Deterministic input",measurement:"Calculated only, not field validation"};assert.equal((await handle(request("reports","POST",p),env)).status,201);const data=JSON.parse(sql.prepare("select data from reports").get().data);assert.match(data.measurement,/not field validation/);assert.equal(sql.prepare("select state from reports").get().state,"new");sql.close();});

test("optional private attachments: token, size, sniffing, limits, retries and authorized download",async()=>{const {env,sql}=setup(),objects=new Map();env.EVIDENCE={async put(k,v){objects.set(k,v);},async get(k){return objects.has(k)?{body:objects.get(k)}:null;}};
const p=payload();await handle(request("reports","POST",p),env);
const send=(id,body="software-only measurement",type="text/plain",token=p.receipt_token)=>new Request("https://uas-handbook.com/api/reports/"+p.id+"/attachments/"+id,{method:"PUT",headers:{authorization:"Bearer "+token,"content-type":type,"x-file-name":"measurement.txt"},body});
const id=crypto.randomUUID();assert.equal((await handle(send(id),env)).status,201);assert.equal((await handle(send(id),env)).status,200);assert.equal((await handle(send(id,"changed"),env)).status,409);assert.equal((await handle(send(crypto.randomUUID(),"x","image/png"),env)).status,400);assert.equal((await handle(send(crypto.randomUUID(),"x","text/plain","wrong"),env)).status,404);assert.equal((await handle(send(crypto.randomUUID(),"x".repeat(2097153)),env)).status,400);
for(let i=0;i<2;i++)assert.equal((await handle(send(crypto.randomUUID()),env)).status,201);assert.equal((await handle(send(crypto.randomUUID()),env)).status,409);
assert.equal((await handle(request("review/attachments/"+id),env)).status,401);const file=await handle(request("review/attachments/"+id,"GET",undefined,env.REVIEW_TOKEN),env);assert.equal(await file.text(),"software-only measurement");assert.equal(file.headers.get("cache-control"),"no-store");assert.match(file.headers.get("content-disposition"),/^attachment/);sql.close();});

test("a stored receipt survives closing and reopening the actual SQLite database",async()=>{const folder=mkdtempSync(join(tmpdir(),"handbook-receipts-")),file=join(folder,"reports.sqlite"),p=payload();try{const first=setup(file);assert.equal((await handle(request("reports","POST",p),first.env)).status,201);first.sql.close();const second=setup(file);assert.equal((await handle(request("reports/"+p.id,"GET",undefined,p.receipt_token),second.env)).status,200);assert.equal((await handle(request("reports","POST",p),second.env)).status,200);second.sql.close();}finally{rmSync(folder,{recursive:true,force:true});}});
