#!/usr/bin/env bash
# sync_from_canonical.sh
#
# Refreshes the handbook's local-dev data snapshot from the canonical sources
# so `pipeline/pie_pipeline_live.py` runs against fresh data.
#
# What this script syncs:
#   data/forge_database.json           ← droneclear_Forge/DroneClear Components Visualizer/
#   data/parts-db/*.json               ← Ai-Project/data/parts-db/
#
# Why:
#   The handbook's data/forge_database.json and data/parts-db/ are local-dev
#   snapshots used by pie_pipeline_live.py and prediction_engine.py for
#   offline work. They are not regenerated by any CI in this repo (the daily
#   PIE pipeline runs in DroneWuKong/Ai-Project). Without periodic refresh
#   they drift from canonical, and local dev runs produce stale predictions.
#
# Usage:
#   bash pipeline/sync_from_canonical.sh           # auto-detect sibling clones
#   FORGE_ROOT=/path/to/droneclear_Forge \
#   AI_ROOT=/path/to/Ai-Project \
#     bash pipeline/sync_from_canonical.sh         # explicit paths
#
# Exit codes:
#   0  — sync completed (or already up to date)
#   1  — couldn't locate canonical sources

set -euo pipefail

# ── locate canonical roots ────────────────────────────────────────────
HANDBOOK_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FORGE_ROOT="${FORGE_ROOT:-${HANDBOOK_ROOT}/../droneclear_Forge}"
AI_ROOT="${AI_ROOT:-${HANDBOOK_ROOT}/../Ai-Project}"

FORGE_DB_SRC="${FORGE_ROOT}/DroneClear Components Visualizer/forge_database.json"
PARTS_DB_SRC="${AI_ROOT}/data/parts-db"

FORGE_DB_DEST="${HANDBOOK_ROOT}/data/forge_database.json"
PARTS_DB_DEST="${HANDBOOK_ROOT}/data/parts-db"

missing=0
if [ ! -f "$FORGE_DB_SRC" ]; then
    echo "::error::canonical forge_database.json not found at: $FORGE_DB_SRC"
    echo "         set FORGE_ROOT to the root of your droneclear_Forge clone"
    missing=1
fi
if [ ! -d "$PARTS_DB_SRC" ]; then
    echo "::error::canonical parts-db not found at: $PARTS_DB_SRC"
    echo "         set AI_ROOT to the root of your Ai-Project clone"
    missing=1
fi
[ "$missing" -eq 1 ] && exit 1

# ── forge_database.json ───────────────────────────────────────────────
SRC_HASH=$(md5sum "$FORGE_DB_SRC" | awk '{print $1}')
DEST_HASH=""
[ -f "$FORGE_DB_DEST" ] && DEST_HASH=$(md5sum "$FORGE_DB_DEST" | awk '{print $1}')

if [ "$SRC_HASH" = "$DEST_HASH" ]; then
    echo "  forge_database.json: up to date"
else
    cp "$FORGE_DB_SRC" "$FORGE_DB_DEST"
    SRC_SIZE=$(wc -c < "$FORGE_DB_SRC")
    echo "  forge_database.json: refreshed (${SRC_SIZE} bytes)"
fi

# ── parts-db/*.json ───────────────────────────────────────────────────
mkdir -p "$PARTS_DB_DEST"
updated=0
unchanged=0
for src in "$PARTS_DB_SRC"/*.json; do
    [ -f "$src" ] || continue
    name=$(basename "$src")
    dest="$PARTS_DB_DEST/$name"
    src_hash=$(md5sum "$src" | awk '{print $1}')
    dest_hash=""
    [ -f "$dest" ] && dest_hash=$(md5sum "$dest" | awk '{print $1}')
    if [ "$src_hash" = "$dest_hash" ]; then
        unchanged=$((unchanged + 1))
    else
        cp "$src" "$dest"
        updated=$((updated + 1))
    fi
done
echo "  parts-db: ${updated} refreshed, ${unchanged} unchanged"

echo
echo "Sync complete. Fresh data is in:"
echo "  $FORGE_DB_DEST"
echo "  $PARTS_DB_DEST/"
echo
echo "You can now run: python3 pipeline/pie_pipeline_live.py"
